version: '3.8'
services:
  nats:
    container_name: nats
    image: nats:latest
    ports:
      - '4222:4222'

  postgres:
    image: postgres:latest
    env_file:
      - .env
    container_name: postgres
    restart: always
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: